// Code generated by tinybind; DO NOT EDIT.

package codegenjson

import (
	"encoding/json"
	"io"

	"github.com/shibukawa/tinybind-go/jsonbind"
)

func init() {
	jsonbind.RegisterDecode[CanonicalDocumentSet](decodeCanonicalDocumentSetBytes)
	jsonbind.RegisterDecode[ProjectState](decodeProjectStateBytes)
	jsonbind.RegisterEncode[ExchangeDocument](encodeExchangeDocument)
	jsonbind.RegisterDecode[MarkdownOptions](decodeMarkdownOptionsBytes)
	jsonbind.RegisterDecode[SQLExportOptions](decodeSQLExportOptionsBytes)
	jsonbind.RegisterDecode[DiagramExportOptions](decodeDiagramExportOptionsBytes)
	jsonbind.RegisterEncode[ExportResult](encodeExportResult)
}

func decodeCanonicalDocumentSetBytes(data []byte) (CanonicalDocumentSet, error) {
	return decodeCanonicalDocumentSetJSON(json.RawMessage(data))
}

func decodeCanonicalDocumentSetJSON(raw json.RawMessage) (CanonicalDocumentSet, error) {
	var out CanonicalDocumentSet
	m, err := jsonbind.RawJSONMap(raw)
	if err != nil {
		return out, err
	}
	if raw, ok := m["formatVersion"]; ok {
		v, err := jsonbind.DecodeJSONInt(raw)
		if err != nil {
			return out, jsonbind.FieldError("formatVersion", "invalid int", err)
		}
		out.FormatVersion = v
	}
	if raw, ok := m["projectId"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("projectID", "invalid string", err)
		}
		out.ProjectID = v
	}
	if raw, ok := m["documents"]; ok {
		v, err := jsonbind.DecodeJSONMapStringString(raw)
		if err != nil {
			return out, err
		}
		out.Documents = v
	}
	return out, nil
}

func decodeProjectStateBytes(data []byte) (ProjectState, error) {
	return decodeProjectStateJSON(json.RawMessage(data))
}

func decodeProjectStateJSON(raw json.RawMessage) (ProjectState, error) {
	var out ProjectState
	m, err := jsonbind.RawJSONMap(raw)
	if err != nil {
		return out, err
	}
	if raw, ok := m["canvases"]; ok {
		arr, err := jsonbind.RawJSONArray(raw)
		if err != nil {
			return out, err
		}
		slice := make([]SourceERDCanvas, 0, len(arr))
		for _, el := range arr {
			item, err := decodeSourceERDCanvasJSON(el)
			if err != nil {
				return out, err
			}
			slice = append(slice, item)
		}
		out.Canvases = slice
	}
	if raw, ok := m["placements"]; ok {
		arr, err := jsonbind.RawJSONArray(raw)
		if err != nil {
			return out, err
		}
		slice := make([]SourceCanvasModelPlacement, 0, len(arr))
		for _, el := range arr {
			item, err := decodeSourceCanvasModelPlacementJSON(el)
			if err != nil {
				return out, err
			}
			slice = append(slice, item)
		}
		out.Placements = slice
	}
	if raw, ok := m["seeds"]; ok {
		arr, err := jsonbind.RawJSONArray(raw)
		if err != nil {
			return out, err
		}
		slice := make([]SourceModel, 0, len(arr))
		for _, el := range arr {
			item, err := decodeSourceModelJSON(el)
			if err != nil {
				return out, err
			}
			slice = append(slice, item)
		}
		out.Seeds = slice
	}
	if raw, ok := m["relationships"]; ok {
		arr, err := jsonbind.RawJSONArray(raw)
		if err != nil {
			return out, err
		}
		slice := make([]SourceRelationship, 0, len(arr))
		for _, el := range arr {
			item, err := decodeSourceRelationshipJSON(el)
			if err != nil {
				return out, err
			}
			slice = append(slice, item)
		}
		out.Relationships = slice
	}
	if raw, ok := m["relationshipReferences"]; ok {
		arr, err := jsonbind.RawJSONArray(raw)
		if err != nil {
			return out, err
		}
		slice := make([]SourceRelationshipReference, 0, len(arr))
		for _, el := range arr {
			item, err := decodeSourceRelationshipReferenceJSON(el)
			if err != nil {
				return out, err
			}
			slice = append(slice, item)
		}
		out.RelationshipReferences = slice
	}
	if raw, ok := m["domains"]; ok {
		arr, err := jsonbind.RawJSONArray(raw)
		if err != nil {
			return out, err
		}
		slice := make([]SourceDomain, 0, len(arr))
		for _, el := range arr {
			item, err := decodeSourceDomainJSON(el)
			if err != nil {
				return out, err
			}
			slice = append(slice, item)
		}
		out.Domains = slice
	}
	if raw, ok := m["vocabularyEntries"]; ok {
		arr, err := jsonbind.RawJSONArray(raw)
		if err != nil {
			return out, err
		}
		slice := make([]SourceVocabularyEntry, 0, len(arr))
		for _, el := range arr {
			item, err := decodeSourceVocabularyEntryJSON(el)
			if err != nil {
				return out, err
			}
			slice = append(slice, item)
		}
		out.VocabularyEntries = slice
	}
	if raw, ok := m["namingPolicy"]; ok {
		v, err := decodeSourceNamingPolicyJSON(raw)
		if err != nil {
			return out, err
		}
		out.NamingPolicy = v
	}
	if raw, ok := m["dfd"]; ok {
		v, err := decodeSourceDFDStateJSON(raw)
		if err != nil {
			return out, err
		}
		out.DFD = v
	}
	if raw, ok := m["annotations"]; ok {
		arr, err := jsonbind.RawJSONArray(raw)
		if err != nil {
			return out, err
		}
		slice := make([]SourceCanvasAnnotation, 0, len(arr))
		for _, el := range arr {
			item, err := decodeSourceCanvasAnnotationJSON(el)
			if err != nil {
				return out, err
			}
			slice = append(slice, item)
		}
		out.Annotations = slice
	}
	return out, nil
}

func decodeSourceERDCanvasBytes(data []byte) (SourceERDCanvas, error) {
	return decodeSourceERDCanvasJSON(json.RawMessage(data))
}

func decodeSourceERDCanvasJSON(raw json.RawMessage) (SourceERDCanvas, error) {
	var out SourceERDCanvas
	m, err := jsonbind.RawJSONMap(raw)
	if err != nil {
		return out, err
	}
	if raw, ok := m["id"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("iD", "invalid string", err)
		}
		out.ID = v
	}
	if raw, ok := m["name"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("name", "invalid string", err)
		}
		out.Name = v
	}
	return out, nil
}

func decodeSourceCanvasModelPlacementBytes(data []byte) (SourceCanvasModelPlacement, error) {
	return decodeSourceCanvasModelPlacementJSON(json.RawMessage(data))
}

func decodeSourceCanvasModelPlacementJSON(raw json.RawMessage) (SourceCanvasModelPlacement, error) {
	var out SourceCanvasModelPlacement
	m, err := jsonbind.RawJSONMap(raw)
	if err != nil {
		return out, err
	}
	if raw, ok := m["canvasId"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("canvasID", "invalid string", err)
		}
		out.CanvasID = v
	}
	if raw, ok := m["seedId"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("seedID", "invalid string", err)
		}
		out.SeedID = v
	}
	if raw, ok := m["x"]; ok {
		v, err := jsonbind.DecodeJSONFloat64(raw)
		if err != nil {
			return out, jsonbind.FieldError("x", "invalid float64", err)
		}
		out.X = v
	}
	if raw, ok := m["y"]; ok {
		v, err := jsonbind.DecodeJSONFloat64(raw)
		if err != nil {
			return out, jsonbind.FieldError("y", "invalid float64", err)
		}
		out.Y = v
	}
	if raw, ok := m["accessMode"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("accessMode", "invalid string", err)
		}
		out.AccessMode = v
	}
	return out, nil
}

func decodeSourceNamingPolicyBytes(data []byte) (SourceNamingPolicy, error) {
	return decodeSourceNamingPolicyJSON(json.RawMessage(data))
}

func decodeSourceNamingPolicyJSON(raw json.RawMessage) (SourceNamingPolicy, error) {
	var out SourceNamingPolicy
	m, err := jsonbind.RawJSONMap(raw)
	if err != nil {
		return out, err
	}
	if raw, ok := m["tablePluralization"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("tablePluralization", "invalid string", err)
		}
		out.TablePluralization = v
	}
	if raw, ok := m["tableJoinMode"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("tableJoinMode", "invalid string", err)
		}
		out.TableJoinMode = v
	}
	if raw, ok := m["tableSeparator"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("tableSeparator", "invalid string", err)
		}
		out.TableSeparator = v
	}
	if raw, ok := m["fieldJoinMode"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("fieldJoinMode", "invalid string", err)
		}
		out.FieldJoinMode = v
	}
	if raw, ok := m["fieldSeparator"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("fieldSeparator", "invalid string", err)
		}
		out.FieldSeparator = v
	}
	if raw, ok := m["domainJoinMode"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("domainJoinMode", "invalid string", err)
		}
		out.DomainJoinMode = v
	}
	if raw, ok := m["domainSeparator"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("domainSeparator", "invalid string", err)
		}
		out.DomainSeparator = v
	}
	return out, nil
}

func decodeNamesBytes(data []byte) (Names, error) {
	return decodeNamesJSON(json.RawMessage(data))
}

func decodeNamesJSON(raw json.RawMessage) (Names, error) {
	var out Names
	m, err := jsonbind.RawJSONMap(raw)
	if err != nil {
		return out, err
	}
	if raw, ok := m["business"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("business", "invalid string", err)
		}
		out.Business = v
	}
	if raw, ok := m["system"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("system", "invalid string", err)
		}
		out.System = v
	}
	if raw, ok := m["physical"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("physical", "invalid string", err)
		}
		out.Physical = v
	}
	return out, nil
}

func encodeNamesMap(v Names) map[string]any {
	body := map[string]any{}
	body["business"] = v.Business
	body["system"] = v.System
	body["physical"] = v.Physical
	return body
}

func encodeNames(w io.Writer, v Names) error {
	return json.NewEncoder(w).Encode(encodeNamesMap(v))
}

func decodeSourceModelBytes(data []byte) (SourceModel, error) {
	return decodeSourceModelJSON(json.RawMessage(data))
}

func decodeSourceModelJSON(raw json.RawMessage) (SourceModel, error) {
	var out SourceModel
	m, err := jsonbind.RawJSONMap(raw)
	if err != nil {
		return out, err
	}
	if raw, ok := m["id"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("iD", "invalid string", err)
		}
		out.ID = v
	}
	if raw, ok := m["title"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("title", "invalid string", err)
		}
		out.Title = v
	}
	if raw, ok := m["names"]; ok {
		v, err := decodeNamesJSON(raw)
		if err != nil {
			return out, err
		}
		out.Names = v
	}
	if raw, ok := m["description"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("description", "invalid string", err)
		}
		out.Description = v
	}
	if raw, ok := m["fields"]; ok {
		arr, err := jsonbind.RawJSONArray(raw)
		if err != nil {
			return out, err
		}
		slice := make([]SourceField, 0, len(arr))
		for _, el := range arr {
			item, err := decodeSourceFieldJSON(el)
			if err != nil {
				return out, err
			}
			slice = append(slice, item)
		}
		out.Fields = slice
	}
	if raw, ok := m["role"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("role", "invalid string", err)
		}
		out.Role = v
	}
	if raw, ok := m["dependency"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("dependency", "invalid string", err)
		}
		out.Dependency = v
	}
	if raw, ok := m["usageScope"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("usageScope", "invalid string", err)
		}
		out.UsageScope = v
	}
	if raw, ok := m["hasPrivacy"]; ok {
		v, err := jsonbind.DecodeJSONBool(raw)
		if err != nil {
			return out, jsonbind.FieldError("hasPrivacy", "invalid bool", err)
		}
		out.HasPrivacy = v
	}
	if raw, ok := m["indexes"]; ok {
		arr, err := jsonbind.RawJSONArray(raw)
		if err != nil {
			return out, err
		}
		slice := make([]SourceIndexDefinition, 0, len(arr))
		for _, el := range arr {
			item, err := decodeSourceIndexDefinitionJSON(el)
			if err != nil {
				return out, err
			}
			slice = append(slice, item)
		}
		out.Indexes = slice
	}
	if raw, ok := m["partitioning"]; ok {
		v, err := decodeSourcePartitionSchemeJSON(raw)
		if err != nil {
			return out, err
		}
		out.Partitioning = v
	}
	if raw, ok := m["volumeEstimate"]; ok {
		v, err := decodeSourceVolumeEstimateJSON(raw)
		if err != nil {
			return out, err
		}
		out.VolumeEstimate = v
	}
	if raw, ok := m["additionalSql"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("additionalSQL", "invalid string", err)
		}
		out.AdditionalSQL = v
	}
	if raw, ok := m["x"]; ok {
		v, err := jsonbind.DecodeJSONFloat64(raw)
		if err != nil {
			return out, jsonbind.FieldError("x", "invalid float64", err)
		}
		out.X = v
	}
	if raw, ok := m["y"]; ok {
		v, err := jsonbind.DecodeJSONFloat64(raw)
		if err != nil {
			return out, jsonbind.FieldError("y", "invalid float64", err)
		}
		out.Y = v
	}
	if raw, ok := m["rotation"]; ok {
		v, err := jsonbind.DecodeJSONFloat64(raw)
		if err != nil {
			return out, jsonbind.FieldError("rotation", "invalid float64", err)
		}
		out.Rotation = v
	}
	if raw, ok := m["maturedLevel"]; ok {
		v, err := jsonbind.DecodeJSONFloat64(raw)
		if err != nil {
			return out, jsonbind.FieldError("maturedLevel", "invalid float64", err)
		}
		out.MaturedLevel = v
	}
	return out, nil
}

func decodeSourceFieldBytes(data []byte) (SourceField, error) {
	return decodeSourceFieldJSON(json.RawMessage(data))
}

func decodeSourceFieldJSON(raw json.RawMessage) (SourceField, error) {
	var out SourceField
	m, err := jsonbind.RawJSONMap(raw)
	if err != nil {
		return out, err
	}
	if raw, ok := m["id"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("iD", "invalid string", err)
		}
		out.ID = v
	}
	if raw, ok := m["name"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("name", "invalid string", err)
		}
		out.Name = v
	}
	if raw, ok := m["names"]; ok {
		v, err := decodeNamesJSON(raw)
		if err != nil {
			return out, err
		}
		out.Names = v
	}
	if raw, ok := m["primaryKey"]; ok {
		v, err := jsonbind.DecodeJSONBool(raw)
		if err != nil {
			return out, jsonbind.FieldError("primaryKey", "invalid bool", err)
		}
		out.PrimaryKey = v
	}
	if raw, ok := m["important"]; ok {
		v, err := jsonbind.DecodeJSONBool(raw)
		if err != nil {
			return out, jsonbind.FieldError("important", "invalid bool", err)
		}
		out.Important = v
	}
	if raw, ok := m["domainId"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("domainID", "invalid string", err)
		}
		out.DomainID = v
	}
	if raw, ok := m["useDomainName"]; ok {
		v, err := jsonbind.DecodeJSONBool(raw)
		if err != nil {
			return out, jsonbind.FieldError("useDomainName", "invalid bool", err)
		}
		out.UseDomainName = v
	}
	if raw, ok := m["required"]; ok {
		v, err := jsonbind.DecodeJSONBool(raw)
		if err != nil {
			return out, jsonbind.FieldError("required", "invalid bool", err)
		}
		out.Required = v
	}
	if raw, ok := m["unique"]; ok {
		v, err := jsonbind.DecodeJSONBool(raw)
		if err != nil {
			return out, jsonbind.FieldError("unique", "invalid bool", err)
		}
		out.Unique = v
	}
	if raw, ok := m["defaultValue"]; ok {
		v, err := decodeSourceColumnDefaultJSON(raw)
		if err != nil {
			return out, err
		}
		out.DefaultValue = v
	}
	if raw, ok := m["valueGeneration"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("valueGeneration", "invalid string", err)
		}
		out.ValueGeneration = v
	}
	if raw, ok := m["estimatedAverageSizeBytes"]; ok {
		v, err := jsonbind.DecodeJSONFloat64(raw)
		if err != nil {
			return out, jsonbind.FieldError("estimatedAverageSizeBytes", "invalid float64", err)
		}
		out.EstimatedAverageSizeBytes = v
	}
	return out, nil
}

func decodeSourceVolumeEstimateBytes(data []byte) (SourceVolumeEstimate, error) {
	return decodeSourceVolumeEstimateJSON(json.RawMessage(data))
}

func decodeSourceVolumeEstimateJSON(raw json.RawMessage) (SourceVolumeEstimate, error) {
	var out SourceVolumeEstimate
	m, err := jsonbind.RawJSONMap(raw)
	if err != nil {
		return out, err
	}
	if raw, ok := m["initialRecordCount"]; ok {
		v, err := jsonbind.DecodeJSONInt(raw)
		if err != nil {
			return out, jsonbind.FieldError("initialRecordCount", "invalid int", err)
		}
		out.InitialRecordCount = v
	}
	if raw, ok := m["growthRate"]; ok {
		v, err := decodeSourceGrowthRateJSON(raw)
		if err != nil {
			return out, err
		}
		out.GrowthRate = v
	}
	if raw, ok := m["retentionPeriod"]; ok {
		v, err := decodeSourceRetentionPeriodJSON(raw)
		if err != nil {
			return out, err
		}
		out.RetentionPeriod = v
	}
	if raw, ok := m["maximumRecordCount"]; ok {
		v, err := jsonbind.DecodeJSONInt(raw)
		if err != nil {
			return out, jsonbind.FieldError("maximumRecordCount", "invalid int", err)
		}
		out.MaximumRecordCount = v
	}
	return out, nil
}

func decodeSourceGrowthRateBytes(data []byte) (SourceGrowthRate, error) {
	return decodeSourceGrowthRateJSON(json.RawMessage(data))
}

func decodeSourceGrowthRateJSON(raw json.RawMessage) (SourceGrowthRate, error) {
	var out SourceGrowthRate
	m, err := jsonbind.RawJSONMap(raw)
	if err != nil {
		return out, err
	}
	if raw, ok := m["amount"]; ok {
		v, err := jsonbind.DecodeJSONInt(raw)
		if err != nil {
			return out, jsonbind.FieldError("amount", "invalid int", err)
		}
		out.Amount = v
	}
	if raw, ok := m["period"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("period", "invalid string", err)
		}
		out.Period = v
	}
	return out, nil
}

func decodeSourceRetentionPeriodBytes(data []byte) (SourceRetentionPeriod, error) {
	return decodeSourceRetentionPeriodJSON(json.RawMessage(data))
}

func decodeSourceRetentionPeriodJSON(raw json.RawMessage) (SourceRetentionPeriod, error) {
	var out SourceRetentionPeriod
	m, err := jsonbind.RawJSONMap(raw)
	if err != nil {
		return out, err
	}
	if raw, ok := m["value"]; ok {
		v, err := jsonbind.DecodeJSONInt(raw)
		if err != nil {
			return out, jsonbind.FieldError("value", "invalid int", err)
		}
		out.Value = v
	}
	if raw, ok := m["unit"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("unit", "invalid string", err)
		}
		out.Unit = v
	}
	return out, nil
}

func decodeSourceColumnDefaultBytes(data []byte) (SourceColumnDefault, error) {
	return decodeSourceColumnDefaultJSON(json.RawMessage(data))
}

func decodeSourceColumnDefaultJSON(raw json.RawMessage) (SourceColumnDefault, error) {
	var out SourceColumnDefault
	m, err := jsonbind.RawJSONMap(raw)
	if err != nil {
		return out, err
	}
	if raw, ok := m["kind"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("kind", "invalid string", err)
		}
		out.Kind = v
	}
	if raw, ok := m["value"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("value", "invalid string", err)
		}
		out.Value = v
	}
	return out, nil
}

func encodeSourceColumnDefaultMap(v SourceColumnDefault) map[string]any {
	body := map[string]any{}
	body["kind"] = v.Kind
	body["value"] = v.Value
	return body
}

func encodeSourceColumnDefault(w io.Writer, v SourceColumnDefault) error {
	return json.NewEncoder(w).Encode(encodeSourceColumnDefaultMap(v))
}

func decodeSourceIndexDefinitionBytes(data []byte) (SourceIndexDefinition, error) {
	return decodeSourceIndexDefinitionJSON(json.RawMessage(data))
}

func decodeSourceIndexDefinitionJSON(raw json.RawMessage) (SourceIndexDefinition, error) {
	var out SourceIndexDefinition
	m, err := jsonbind.RawJSONMap(raw)
	if err != nil {
		return out, err
	}
	if raw, ok := m["id"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("iD", "invalid string", err)
		}
		out.ID = v
	}
	if raw, ok := m["name"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("name", "invalid string", err)
		}
		out.Name = v
	}
	if raw, ok := m["unique"]; ok {
		v, err := jsonbind.DecodeJSONBool(raw)
		if err != nil {
			return out, jsonbind.FieldError("unique", "invalid bool", err)
		}
		out.Unique = v
	}
	if raw, ok := m["keys"]; ok {
		arr, err := jsonbind.RawJSONArray(raw)
		if err != nil {
			return out, err
		}
		slice := make([]SourceIndexKey, 0, len(arr))
		for _, el := range arr {
			item, err := decodeSourceIndexKeyJSON(el)
			if err != nil {
				return out, err
			}
			slice = append(slice, item)
		}
		out.Keys = slice
	}
	return out, nil
}

func encodeSourceIndexDefinitionMap(v SourceIndexDefinition) map[string]any {
	body := map[string]any{}
	body["id"] = v.ID
	body["name"] = v.Name
	body["unique"] = v.Unique
	{
		arr := make([]any, len(v.Keys))
		for i := range v.Keys {
			arr[i] = encodeSourceIndexKeyMap(v.Keys[i])
		}
		body["keys"] = arr
	}
	return body
}

func encodeSourceIndexDefinition(w io.Writer, v SourceIndexDefinition) error {
	return json.NewEncoder(w).Encode(encodeSourceIndexDefinitionMap(v))
}

func decodeSourceIndexKeyBytes(data []byte) (SourceIndexKey, error) {
	return decodeSourceIndexKeyJSON(json.RawMessage(data))
}

func decodeSourceIndexKeyJSON(raw json.RawMessage) (SourceIndexKey, error) {
	var out SourceIndexKey
	m, err := jsonbind.RawJSONMap(raw)
	if err != nil {
		return out, err
	}
	if raw, ok := m["source"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("source", "invalid string", err)
		}
		out.Source = v
	}
	if raw, ok := m["sourceId"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("sourceID", "invalid string", err)
		}
		out.SourceID = v
	}
	if raw, ok := m["componentId"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("componentID", "invalid string", err)
		}
		out.ComponentID = v
	}
	if raw, ok := m["direction"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("direction", "invalid string", err)
		}
		out.Direction = v
	}
	return out, nil
}

func encodeSourceIndexKeyMap(v SourceIndexKey) map[string]any {
	body := map[string]any{}
	body["source"] = v.Source
	body["sourceId"] = v.SourceID
	body["componentId"] = v.ComponentID
	body["direction"] = v.Direction
	return body
}

func encodeSourceIndexKey(w io.Writer, v SourceIndexKey) error {
	return json.NewEncoder(w).Encode(encodeSourceIndexKeyMap(v))
}

func decodeSourcePartitionSchemeBytes(data []byte) (SourcePartitionScheme, error) {
	return decodeSourcePartitionSchemeJSON(json.RawMessage(data))
}

func decodeSourcePartitionSchemeJSON(raw json.RawMessage) (SourcePartitionScheme, error) {
	var out SourcePartitionScheme
	m, err := jsonbind.RawJSONMap(raw)
	if err != nil {
		return out, err
	}
	if raw, ok := m["strategy"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("strategy", "invalid string", err)
		}
		out.Strategy = v
	}
	if raw, ok := m["keys"]; ok {
		arr, err := jsonbind.RawJSONArray(raw)
		if err != nil {
			return out, err
		}
		slice := make([]SourcePartitionKey, 0, len(arr))
		for _, el := range arr {
			item, err := decodeSourcePartitionKeyJSON(el)
			if err != nil {
				return out, err
			}
			slice = append(slice, item)
		}
		out.Keys = slice
	}
	if raw, ok := m["ranges"]; ok {
		arr, err := jsonbind.RawJSONArray(raw)
		if err != nil {
			return out, err
		}
		slice := make([]SourcePartitionRange, 0, len(arr))
		for _, el := range arr {
			item, err := decodeSourcePartitionRangeJSON(el)
			if err != nil {
				return out, err
			}
			slice = append(slice, item)
		}
		out.Ranges = slice
	}
	return out, nil
}

func encodeSourcePartitionSchemeMap(v SourcePartitionScheme) map[string]any {
	body := map[string]any{}
	body["strategy"] = v.Strategy
	{
		arr := make([]any, len(v.Keys))
		for i := range v.Keys {
			arr[i] = encodeSourcePartitionKeyMap(v.Keys[i])
		}
		body["keys"] = arr
	}
	{
		arr := make([]any, len(v.Ranges))
		for i := range v.Ranges {
			arr[i] = encodeSourcePartitionRangeMap(v.Ranges[i])
		}
		body["ranges"] = arr
	}
	return body
}

func encodeSourcePartitionScheme(w io.Writer, v SourcePartitionScheme) error {
	return json.NewEncoder(w).Encode(encodeSourcePartitionSchemeMap(v))
}

func decodeSourcePartitionKeyBytes(data []byte) (SourcePartitionKey, error) {
	return decodeSourcePartitionKeyJSON(json.RawMessage(data))
}

func decodeSourcePartitionKeyJSON(raw json.RawMessage) (SourcePartitionKey, error) {
	var out SourcePartitionKey
	m, err := jsonbind.RawJSONMap(raw)
	if err != nil {
		return out, err
	}
	if raw, ok := m["fieldId"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("fieldID", "invalid string", err)
		}
		out.FieldID = v
	}
	if raw, ok := m["componentId"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("componentID", "invalid string", err)
		}
		out.ComponentID = v
	}
	return out, nil
}

func encodeSourcePartitionKeyMap(v SourcePartitionKey) map[string]any {
	body := map[string]any{}
	body["fieldId"] = v.FieldID
	body["componentId"] = v.ComponentID
	return body
}

func encodeSourcePartitionKey(w io.Writer, v SourcePartitionKey) error {
	return json.NewEncoder(w).Encode(encodeSourcePartitionKeyMap(v))
}

func decodeSourcePartitionRangeBytes(data []byte) (SourcePartitionRange, error) {
	return decodeSourcePartitionRangeJSON(json.RawMessage(data))
}

func decodeSourcePartitionRangeJSON(raw json.RawMessage) (SourcePartitionRange, error) {
	var out SourcePartitionRange
	m, err := jsonbind.RawJSONMap(raw)
	if err != nil {
		return out, err
	}
	if raw, ok := m["id"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("iD", "invalid string", err)
		}
		out.ID = v
	}
	if raw, ok := m["name"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("name", "invalid string", err)
		}
		out.Name = v
	}
	if raw, ok := m["from"]; ok {
		arr, err := jsonbind.RawJSONArray(raw)
		if err != nil {
			return out, err
		}
		slice := make([]SourcePartitionBound, 0, len(arr))
		for _, el := range arr {
			item, err := decodeSourcePartitionBoundJSON(el)
			if err != nil {
				return out, err
			}
			slice = append(slice, item)
		}
		out.From = slice
	}
	if raw, ok := m["to"]; ok {
		arr, err := jsonbind.RawJSONArray(raw)
		if err != nil {
			return out, err
		}
		slice := make([]SourcePartitionBound, 0, len(arr))
		for _, el := range arr {
			item, err := decodeSourcePartitionBoundJSON(el)
			if err != nil {
				return out, err
			}
			slice = append(slice, item)
		}
		out.To = slice
	}
	return out, nil
}

func encodeSourcePartitionRangeMap(v SourcePartitionRange) map[string]any {
	body := map[string]any{}
	body["id"] = v.ID
	body["name"] = v.Name
	{
		arr := make([]any, len(v.From))
		for i := range v.From {
			arr[i] = encodeSourcePartitionBoundMap(v.From[i])
		}
		body["from"] = arr
	}
	{
		arr := make([]any, len(v.To))
		for i := range v.To {
			arr[i] = encodeSourcePartitionBoundMap(v.To[i])
		}
		body["to"] = arr
	}
	return body
}

func encodeSourcePartitionRange(w io.Writer, v SourcePartitionRange) error {
	return json.NewEncoder(w).Encode(encodeSourcePartitionRangeMap(v))
}

func decodeSourcePartitionBoundBytes(data []byte) (SourcePartitionBound, error) {
	return decodeSourcePartitionBoundJSON(json.RawMessage(data))
}

func decodeSourcePartitionBoundJSON(raw json.RawMessage) (SourcePartitionBound, error) {
	var out SourcePartitionBound
	m, err := jsonbind.RawJSONMap(raw)
	if err != nil {
		return out, err
	}
	if raw, ok := m["kind"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("kind", "invalid string", err)
		}
		out.Kind = v
	}
	if raw, ok := m["value"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("value", "invalid string", err)
		}
		out.Value = v
	}
	return out, nil
}

func encodeSourcePartitionBoundMap(v SourcePartitionBound) map[string]any {
	body := map[string]any{}
	body["kind"] = v.Kind
	body["value"] = v.Value
	return body
}

func encodeSourcePartitionBound(w io.Writer, v SourcePartitionBound) error {
	return json.NewEncoder(w).Encode(encodeSourcePartitionBoundMap(v))
}

func decodeSourceDomainBytes(data []byte) (SourceDomain, error) {
	return decodeSourceDomainJSON(json.RawMessage(data))
}

func decodeSourceDomainJSON(raw json.RawMessage) (SourceDomain, error) {
	var out SourceDomain
	m, err := jsonbind.RawJSONMap(raw)
	if err != nil {
		return out, err
	}
	if raw, ok := m["id"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("iD", "invalid string", err)
		}
		out.ID = v
	}
	if raw, ok := m["name"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("name", "invalid string", err)
		}
		out.Name = v
	}
	if raw, ok := m["names"]; ok {
		v, err := decodeNamesJSON(raw)
		if err != nil {
			return out, err
		}
		out.Names = v
	}
	if raw, ok := m["categoryId"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("categoryID", "invalid string", err)
		}
		out.CategoryID = v
	}
	if raw, ok := m["shape"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("shape", "invalid string", err)
		}
		out.Shape = v
	}
	if raw, ok := m["primitiveType"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("primitiveType", "invalid string", err)
		}
		out.PrimitiveType = v
	}
	if raw, ok := m["bits"]; ok {
		v, err := jsonbind.DecodeJSONInt(raw)
		if err != nil {
			return out, jsonbind.FieldError("bits", "invalid int", err)
		}
		out.Bits = v
	}
	if raw, ok := m["unsigned"]; ok {
		v, err := jsonbind.DecodeJSONBool(raw)
		if err != nil {
			return out, jsonbind.FieldError("unsigned", "invalid bool", err)
		}
		out.Unsigned = v
	}
	if raw, ok := m["length"]; ok {
		v, err := jsonbind.DecodeJSONInt(raw)
		if err != nil {
			return out, jsonbind.FieldError("length", "invalid int", err)
		}
		out.Length = v
	}
	if raw, ok := m["precision"]; ok {
		v, err := jsonbind.DecodeJSONInt(raw)
		if err != nil {
			return out, jsonbind.FieldError("precision", "invalid int", err)
		}
		out.Precision = v
	}
	if raw, ok := m["scale"]; ok {
		v, err := jsonbind.DecodeJSONInt(raw)
		if err != nil {
			return out, jsonbind.FieldError("scale", "invalid int", err)
		}
		out.Scale = v
	}
	if raw, ok := m["codeSetBaseType"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("codeSetBaseType", "invalid string", err)
		}
		out.CodeSetBaseType = v
	}
	if raw, ok := m["codeSetEntries"]; ok {
		arr, err := jsonbind.RawJSONArray(raw)
		if err != nil {
			return out, err
		}
		slice := make([]SourceCodeSetEntry, 0, len(arr))
		for _, el := range arr {
			item, err := decodeSourceCodeSetEntryJSON(el)
			if err != nil {
				return out, err
			}
			slice = append(slice, item)
		}
		out.CodeSetEntries = slice
	}
	if raw, ok := m["components"]; ok {
		arr, err := jsonbind.RawJSONArray(raw)
		if err != nil {
			return out, err
		}
		slice := make([]SourceDomainComponent, 0, len(arr))
		for _, el := range arr {
			item, err := decodeSourceDomainComponentJSON(el)
			if err != nil {
				return out, err
			}
			slice = append(slice, item)
		}
		out.Components = slice
	}
	if raw, ok := m["partitionKey"]; ok {
		v, err := jsonbind.DecodeJSONBool(raw)
		if err != nil {
			return out, jsonbind.FieldError("partitionKey", "invalid bool", err)
		}
		out.PartitionKey = v
	}
	if raw, ok := m["system"]; ok {
		v, err := jsonbind.DecodeJSONBool(raw)
		if err != nil {
			return out, jsonbind.FieldError("system", "invalid bool", err)
		}
		out.System = v
	}
	return out, nil
}

func decodeSourceDomainComponentBytes(data []byte) (SourceDomainComponent, error) {
	return decodeSourceDomainComponentJSON(json.RawMessage(data))
}

func decodeSourceDomainComponentJSON(raw json.RawMessage) (SourceDomainComponent, error) {
	var out SourceDomainComponent
	m, err := jsonbind.RawJSONMap(raw)
	if err != nil {
		return out, err
	}
	if raw, ok := m["id"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("iD", "invalid string", err)
		}
		out.ID = v
	}
	if raw, ok := m["name"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("name", "invalid string", err)
		}
		out.Name = v
	}
	if raw, ok := m["domainId"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("domainID", "invalid string", err)
		}
		out.DomainID = v
	}
	if raw, ok := m["required"]; ok {
		v, err := jsonbind.DecodeJSONBool(raw)
		if err != nil {
			return out, jsonbind.FieldError("required", "invalid bool", err)
		}
		out.Required = v
	}
	if raw, ok := m["description"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("description", "invalid string", err)
		}
		out.Description = v
	}
	if raw, ok := m["partitionKey"]; ok {
		v, err := jsonbind.DecodeJSONBool(raw)
		if err != nil {
			return out, jsonbind.FieldError("partitionKey", "invalid bool", err)
		}
		out.PartitionKey = v
	}
	return out, nil
}

func encodeSourceDomainComponentMap(v SourceDomainComponent) map[string]any {
	body := map[string]any{}
	body["id"] = v.ID
	body["name"] = v.Name
	body["domainId"] = v.DomainID
	body["required"] = v.Required
	body["description"] = v.Description
	body["partitionKey"] = v.PartitionKey
	return body
}

func encodeSourceDomainComponent(w io.Writer, v SourceDomainComponent) error {
	return json.NewEncoder(w).Encode(encodeSourceDomainComponentMap(v))
}

func decodeSourceCodeSetEntryBytes(data []byte) (SourceCodeSetEntry, error) {
	return decodeSourceCodeSetEntryJSON(json.RawMessage(data))
}

func decodeSourceCodeSetEntryJSON(raw json.RawMessage) (SourceCodeSetEntry, error) {
	var out SourceCodeSetEntry
	m, err := jsonbind.RawJSONMap(raw)
	if err != nil {
		return out, err
	}
	if raw, ok := m["id"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("iD", "invalid string", err)
		}
		out.ID = v
	}
	if raw, ok := m["name"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("name", "invalid string", err)
		}
		out.Name = v
	}
	if raw, ok := m["value"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("value", "invalid string", err)
		}
		out.Value = v
	}
	return out, nil
}

func encodeSourceCodeSetEntryMap(v SourceCodeSetEntry) map[string]any {
	body := map[string]any{}
	body["id"] = v.ID
	body["name"] = v.Name
	body["value"] = v.Value
	return body
}

func encodeSourceCodeSetEntry(w io.Writer, v SourceCodeSetEntry) error {
	return json.NewEncoder(w).Encode(encodeSourceCodeSetEntryMap(v))
}

func decodeSourceVocabularyEntryBytes(data []byte) (SourceVocabularyEntry, error) {
	return decodeSourceVocabularyEntryJSON(json.RawMessage(data))
}

func decodeSourceVocabularyEntryJSON(raw json.RawMessage) (SourceVocabularyEntry, error) {
	var out SourceVocabularyEntry
	m, err := jsonbind.RawJSONMap(raw)
	if err != nil {
		return out, err
	}
	if raw, ok := m["id"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("iD", "invalid string", err)
		}
		out.ID = v
	}
	if raw, ok := m["businessName"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("businessName", "invalid string", err)
		}
		out.BusinessName = v
	}
	if raw, ok := m["systemName"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("systemName", "invalid string", err)
		}
		out.SystemName = v
	}
	if raw, ok := m["physicalName"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("physicalName", "invalid string", err)
		}
		out.PhysicalName = v
	}
	if raw, ok := m["meaning"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("meaning", "invalid string", err)
		}
		out.Meaning = v
	}
	if raw, ok := m["memo"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("memo", "invalid string", err)
		}
		out.Memo = v
	}
	if raw, ok := m["aliases"]; ok {
		v, err := jsonbind.DecodeJSONStringSlice(raw)
		if err != nil {
			return out, err
		}
		out.Aliases = v
	}
	return out, nil
}

func decodeSourceRelationshipBytes(data []byte) (SourceRelationship, error) {
	return decodeSourceRelationshipJSON(json.RawMessage(data))
}

func decodeSourceRelationshipJSON(raw json.RawMessage) (SourceRelationship, error) {
	var out SourceRelationship
	m, err := jsonbind.RawJSONMap(raw)
	if err != nil {
		return out, err
	}
	if raw, ok := m["id"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("iD", "invalid string", err)
		}
		out.ID = v
	}
	if raw, ok := m["name"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("name", "invalid string", err)
		}
		out.Name = v
	}
	if raw, ok := m["sourceId"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("sourceID", "invalid string", err)
		}
		out.SourceID = v
	}
	if raw, ok := m["targetId"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("targetID", "invalid string", err)
		}
		out.TargetID = v
	}
	if raw, ok := m["sourceMultiplicity"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("sourceMultiplicity", "invalid string", err)
		}
		out.SourceMultiplicity = v
	}
	if raw, ok := m["targetMultiplicity"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("targetMultiplicity", "invalid string", err)
		}
		out.TargetMultiplicity = v
	}
	if raw, ok := m["direction"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("direction", "invalid string", err)
		}
		out.Direction = v
	}
	if raw, ok := m["kind"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("kind", "invalid string", err)
		}
		out.Kind = v
	}
	if raw, ok := m["onDelete"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("onDelete", "invalid string", err)
		}
		out.OnDelete = v
	}
	return out, nil
}

func decodeSourceRelationshipReferenceBytes(data []byte) (SourceRelationshipReference, error) {
	return decodeSourceRelationshipReferenceJSON(json.RawMessage(data))
}

func decodeSourceRelationshipReferenceJSON(raw json.RawMessage) (SourceRelationshipReference, error) {
	var out SourceRelationshipReference
	m, err := jsonbind.RawJSONMap(raw)
	if err != nil {
		return out, err
	}
	if raw, ok := m["id"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("iD", "invalid string", err)
		}
		out.ID = v
	}
	if raw, ok := m["relationshipId"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("relationshipID", "invalid string", err)
		}
		out.RelationshipID = v
	}
	if raw, ok := m["primaryKey"]; ok {
		v, err := jsonbind.DecodeJSONBool(raw)
		if err != nil {
			return out, jsonbind.FieldError("primaryKey", "invalid bool", err)
		}
		out.PrimaryKey = v
	}
	if raw, ok := m["foreignKey"]; ok {
		v, err := jsonbind.DecodeJSONBool(raw)
		if err != nil {
			return out, jsonbind.FieldError("foreignKey", "invalid bool", err)
		}
		out.ForeignKey = v
	}
	if raw, ok := m["hiddenOnModelIds"]; ok {
		v, err := jsonbind.DecodeJSONStringSlice(raw)
		if err != nil {
			return out, err
		}
		out.HiddenOnModelIDs = v
	}
	return out, nil
}

func decodeSourceDFDStateBytes(data []byte) (SourceDFDState, error) {
	return decodeSourceDFDStateJSON(json.RawMessage(data))
}

func decodeSourceDFDStateJSON(raw json.RawMessage) (SourceDFDState, error) {
	var out SourceDFDState
	m, err := jsonbind.RawJSONMap(raw)
	if err != nil {
		return out, err
	}
	if raw, ok := m["canvases"]; ok {
		arr, err := jsonbind.RawJSONArray(raw)
		if err != nil {
			return out, err
		}
		slice := make([]SourceDFDCanvas, 0, len(arr))
		for _, el := range arr {
			item, err := decodeSourceDFDCanvasJSON(el)
			if err != nil {
				return out, err
			}
			slice = append(slice, item)
		}
		out.Canvases = slice
	}
	if raw, ok := m["nodes"]; ok {
		arr, err := jsonbind.RawJSONArray(raw)
		if err != nil {
			return out, err
		}
		slice := make([]SourceDFDNode, 0, len(arr))
		for _, el := range arr {
			item, err := decodeSourceDFDNodeJSON(el)
			if err != nil {
				return out, err
			}
			slice = append(slice, item)
		}
		out.Nodes = slice
	}
	if raw, ok := m["flows"]; ok {
		arr, err := jsonbind.RawJSONArray(raw)
		if err != nil {
			return out, err
		}
		slice := make([]SourceDFDFlow, 0, len(arr))
		for _, el := range arr {
			item, err := decodeSourceDFDFlowJSON(el)
			if err != nil {
				return out, err
			}
			slice = append(slice, item)
		}
		out.Flows = slice
	}
	if raw, ok := m["groups"]; ok {
		arr, err := jsonbind.RawJSONArray(raw)
		if err != nil {
			return out, err
		}
		slice := make([]SourceDFDGroup, 0, len(arr))
		for _, el := range arr {
			item, err := decodeSourceDFDGroupJSON(el)
			if err != nil {
				return out, err
			}
			slice = append(slice, item)
		}
		out.Groups = slice
	}
	if raw, ok := m["crudMatrix"]; ok {
		v, err := decodeSourceCRUDMatrixJSON(raw)
		if err != nil {
			return out, err
		}
		out.CRUDMatrix = v
	}
	return out, nil
}

func decodeSourceDFDCanvasBytes(data []byte) (SourceDFDCanvas, error) {
	return decodeSourceDFDCanvasJSON(json.RawMessage(data))
}

func decodeSourceDFDCanvasJSON(raw json.RawMessage) (SourceDFDCanvas, error) {
	var out SourceDFDCanvas
	m, err := jsonbind.RawJSONMap(raw)
	if err != nil {
		return out, err
	}
	if raw, ok := m["id"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("iD", "invalid string", err)
		}
		out.ID = v
	}
	if raw, ok := m["name"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("name", "invalid string", err)
		}
		out.Name = v
	}
	return out, nil
}

func decodeSourceDFDNodeBytes(data []byte) (SourceDFDNode, error) {
	return decodeSourceDFDNodeJSON(json.RawMessage(data))
}

func decodeSourceDFDNodeJSON(raw json.RawMessage) (SourceDFDNode, error) {
	var out SourceDFDNode
	m, err := jsonbind.RawJSONMap(raw)
	if err != nil {
		return out, err
	}
	if raw, ok := m["id"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("iD", "invalid string", err)
		}
		out.ID = v
	}
	if raw, ok := m["definitionId"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("definitionID", "invalid string", err)
		}
		out.DefinitionID = v
	}
	if raw, ok := m["canvasId"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("canvasID", "invalid string", err)
		}
		out.CanvasID = v
	}
	if raw, ok := m["kind"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("kind", "invalid string", err)
		}
		out.Kind = v
	}
	if raw, ok := m["name"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("name", "invalid string", err)
		}
		out.Name = v
	}
	if raw, ok := m["description"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("description", "invalid string", err)
		}
		out.Description = v
	}
	if raw, ok := m["x"]; ok {
		v, err := jsonbind.DecodeJSONFloat64(raw)
		if err != nil {
			return out, jsonbind.FieldError("x", "invalid float64", err)
		}
		out.X = v
	}
	if raw, ok := m["y"]; ok {
		v, err := jsonbind.DecodeJSONFloat64(raw)
		if err != nil {
			return out, jsonbind.FieldError("y", "invalid float64", err)
		}
		out.Y = v
	}
	if raw, ok := m["processKind"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("processKind", "invalid string", err)
		}
		out.ProcessKind = v
	}
	if raw, ok := m["physicalProcesses"]; ok {
		arr, err := jsonbind.RawJSONArray(raw)
		if err != nil {
			return out, err
		}
		slice := make([]SourceDFDPhysicalProcess, 0, len(arr))
		for _, el := range arr {
			item, err := decodeSourceDFDPhysicalProcessJSON(el)
			if err != nil {
				return out, err
			}
			slice = append(slice, item)
		}
		out.PhysicalProcesses = slice
	}
	if raw, ok := m["modelId"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("modelID", "invalid string", err)
		}
		out.ModelID = v
	}
	if raw, ok := m["intermediateKind"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("intermediateKind", "invalid string", err)
		}
		out.IntermediateKind = v
	}
	if raw, ok := m["format"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("format", "invalid string", err)
		}
		out.Format = v
	}
	return out, nil
}

func decodeSourceDFDGroupBytes(data []byte) (SourceDFDGroup, error) {
	return decodeSourceDFDGroupJSON(json.RawMessage(data))
}

func decodeSourceDFDGroupJSON(raw json.RawMessage) (SourceDFDGroup, error) {
	var out SourceDFDGroup
	m, err := jsonbind.RawJSONMap(raw)
	if err != nil {
		return out, err
	}
	if raw, ok := m["id"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("iD", "invalid string", err)
		}
		out.ID = v
	}
	if raw, ok := m["canvasId"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("canvasID", "invalid string", err)
		}
		out.CanvasID = v
	}
	if raw, ok := m["kind"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("kind", "invalid string", err)
		}
		out.Kind = v
	}
	if raw, ok := m["memberIds"]; ok {
		v, err := jsonbind.DecodeJSONStringSlice(raw)
		if err != nil {
			return out, err
		}
		out.MemberIDs = v
	}
	return out, nil
}

func decodeSourceCRUDMatrixBytes(data []byte) (SourceCRUDMatrix, error) {
	return decodeSourceCRUDMatrixJSON(json.RawMessage(data))
}

func decodeSourceCRUDMatrixJSON(raw json.RawMessage) (SourceCRUDMatrix, error) {
	var out SourceCRUDMatrix
	m, err := jsonbind.RawJSONMap(raw)
	if err != nil {
		return out, err
	}
	if raw, ok := m["orientation"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("orientation", "invalid string", err)
		}
		out.Orientation = v
	}
	if raw, ok := m["processOrder"]; ok {
		v, err := jsonbind.DecodeJSONStringSlice(raw)
		if err != nil {
			return out, err
		}
		out.ProcessOrder = v
	}
	if raw, ok := m["modelOrder"]; ok {
		v, err := jsonbind.DecodeJSONStringSlice(raw)
		if err != nil {
			return out, err
		}
		out.ModelOrder = v
	}
	return out, nil
}

func decodeSourceDFDPhysicalProcessBytes(data []byte) (SourceDFDPhysicalProcess, error) {
	return decodeSourceDFDPhysicalProcessJSON(json.RawMessage(data))
}

func decodeSourceDFDPhysicalProcessJSON(raw json.RawMessage) (SourceDFDPhysicalProcess, error) {
	var out SourceDFDPhysicalProcess
	m, err := jsonbind.RawJSONMap(raw)
	if err != nil {
		return out, err
	}
	if raw, ok := m["id"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("iD", "invalid string", err)
		}
		out.ID = v
	}
	if raw, ok := m["name"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("name", "invalid string", err)
		}
		out.Name = v
	}
	return out, nil
}

func encodeSourceDFDPhysicalProcessMap(v SourceDFDPhysicalProcess) map[string]any {
	body := map[string]any{}
	body["id"] = v.ID
	body["name"] = v.Name
	return body
}

func encodeSourceDFDPhysicalProcess(w io.Writer, v SourceDFDPhysicalProcess) error {
	return json.NewEncoder(w).Encode(encodeSourceDFDPhysicalProcessMap(v))
}

func decodeSourceDFDFlowBytes(data []byte) (SourceDFDFlow, error) {
	return decodeSourceDFDFlowJSON(json.RawMessage(data))
}

func decodeSourceDFDFlowJSON(raw json.RawMessage) (SourceDFDFlow, error) {
	var out SourceDFDFlow
	m, err := jsonbind.RawJSONMap(raw)
	if err != nil {
		return out, err
	}
	if raw, ok := m["id"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("iD", "invalid string", err)
		}
		out.ID = v
	}
	if raw, ok := m["canvasId"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("canvasID", "invalid string", err)
		}
		out.CanvasID = v
	}
	if raw, ok := m["sourceId"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("sourceID", "invalid string", err)
		}
		out.SourceID = v
	}
	if raw, ok := m["destinationId"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("destinationID", "invalid string", err)
		}
		out.DestinationID = v
	}
	if raw, ok := m["label"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("label", "invalid string", err)
		}
		out.Label = v
	}
	if raw, ok := m["protocol"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("protocol", "invalid string", err)
		}
		out.Protocol = v
	}
	if raw, ok := m["bidirectional"]; ok {
		v, err := jsonbind.DecodeJSONBool(raw)
		if err != nil {
			return out, jsonbind.FieldError("bidirectional", "invalid bool", err)
		}
		out.Bidirectional = v
	}
	if raw, ok := m["crudAssignments"]; ok {
		arr, err := jsonbind.RawJSONArray(raw)
		if err != nil {
			return out, err
		}
		slice := make([]SourceCRUDAssignment, 0, len(arr))
		for _, el := range arr {
			item, err := decodeSourceCRUDAssignmentJSON(el)
			if err != nil {
				return out, err
			}
			slice = append(slice, item)
		}
		out.CRUDAssignments = slice
	}
	return out, nil
}

func decodeSourceCRUDAssignmentBytes(data []byte) (SourceCRUDAssignment, error) {
	return decodeSourceCRUDAssignmentJSON(json.RawMessage(data))
}

func decodeSourceCRUDAssignmentJSON(raw json.RawMessage) (SourceCRUDAssignment, error) {
	var out SourceCRUDAssignment
	m, err := jsonbind.RawJSONMap(raw)
	if err != nil {
		return out, err
	}
	if raw, ok := m["processUnitId"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("processUnitID", "invalid string", err)
		}
		out.ProcessUnitID = v
	}
	if raw, ok := m["modelId"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("modelID", "invalid string", err)
		}
		out.ModelID = v
	}
	if raw, ok := m["operations"]; ok {
		v, err := jsonbind.DecodeJSONStringSlice(raw)
		if err != nil {
			return out, err
		}
		out.Operations = v
	}
	return out, nil
}

func decodeSourceCanvasPointBytes(data []byte) (SourceCanvasPoint, error) {
	return decodeSourceCanvasPointJSON(json.RawMessage(data))
}

func decodeSourceCanvasPointJSON(raw json.RawMessage) (SourceCanvasPoint, error) {
	var out SourceCanvasPoint
	m, err := jsonbind.RawJSONMap(raw)
	if err != nil {
		return out, err
	}
	if raw, ok := m["x"]; ok {
		v, err := jsonbind.DecodeJSONFloat64(raw)
		if err != nil {
			return out, jsonbind.FieldError("x", "invalid float64", err)
		}
		out.X = v
	}
	if raw, ok := m["y"]; ok {
		v, err := jsonbind.DecodeJSONFloat64(raw)
		if err != nil {
			return out, jsonbind.FieldError("y", "invalid float64", err)
		}
		out.Y = v
	}
	return out, nil
}

func decodeSourceAnnotationStrokeBytes(data []byte) (SourceAnnotationStroke, error) {
	return decodeSourceAnnotationStrokeJSON(json.RawMessage(data))
}

func decodeSourceAnnotationStrokeJSON(raw json.RawMessage) (SourceAnnotationStroke, error) {
	var out SourceAnnotationStroke
	m, err := jsonbind.RawJSONMap(raw)
	if err != nil {
		return out, err
	}
	if raw, ok := m["points"]; ok {
		arr, err := jsonbind.RawJSONArray(raw)
		if err != nil {
			return out, err
		}
		slice := make([]SourceCanvasPoint, 0, len(arr))
		for _, el := range arr {
			item, err := decodeSourceCanvasPointJSON(el)
			if err != nil {
				return out, err
			}
			slice = append(slice, item)
		}
		out.Points = slice
	}
	return out, nil
}

func decodeSourceAnnotationAnchorBytes(data []byte) (SourceAnnotationAnchor, error) {
	return decodeSourceAnnotationAnchorJSON(json.RawMessage(data))
}

func decodeSourceAnnotationAnchorJSON(raw json.RawMessage) (SourceAnnotationAnchor, error) {
	var out SourceAnnotationAnchor
	m, err := jsonbind.RawJSONMap(raw)
	if err != nil {
		return out, err
	}
	if raw, ok := m["x"]; ok {
		v, err := jsonbind.DecodeJSONFloat64(raw)
		if err != nil {
			return out, jsonbind.FieldError("x", "invalid float64", err)
		}
		out.X = v
	}
	if raw, ok := m["y"]; ok {
		v, err := jsonbind.DecodeJSONFloat64(raw)
		if err != nil {
			return out, jsonbind.FieldError("y", "invalid float64", err)
		}
		out.Y = v
	}
	if raw, ok := m["itemId"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("itemID", "invalid string", err)
		}
		out.ItemID = v
	}
	if raw, ok := m["itemKind"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("itemKind", "invalid string", err)
		}
		out.ItemKind = v
	}
	return out, nil
}

func decodeSourceCanvasAnnotationBytes(data []byte) (SourceCanvasAnnotation, error) {
	return decodeSourceCanvasAnnotationJSON(json.RawMessage(data))
}

func decodeSourceCanvasAnnotationJSON(raw json.RawMessage) (SourceCanvasAnnotation, error) {
	var out SourceCanvasAnnotation
	m, err := jsonbind.RawJSONMap(raw)
	if err != nil {
		return out, err
	}
	if raw, ok := m["id"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("iD", "invalid string", err)
		}
		out.ID = v
	}
	if raw, ok := m["canvasType"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("canvasType", "invalid string", err)
		}
		out.CanvasType = v
	}
	if raw, ok := m["canvasId"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("canvasID", "invalid string", err)
		}
		out.CanvasID = v
	}
	if raw, ok := m["kind"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("kind", "invalid string", err)
		}
		out.Kind = v
	}
	if raw, ok := m["x"]; ok {
		v, err := jsonbind.DecodeJSONFloat64(raw)
		if err != nil {
			return out, jsonbind.FieldError("x", "invalid float64", err)
		}
		out.X = v
	}
	if raw, ok := m["y"]; ok {
		v, err := jsonbind.DecodeJSONFloat64(raw)
		if err != nil {
			return out, jsonbind.FieldError("y", "invalid float64", err)
		}
		out.Y = v
	}
	if raw, ok := m["width"]; ok {
		v, err := jsonbind.DecodeJSONFloat64(raw)
		if err != nil {
			return out, jsonbind.FieldError("width", "invalid float64", err)
		}
		out.Width = v
	}
	if raw, ok := m["height"]; ok {
		v, err := jsonbind.DecodeJSONFloat64(raw)
		if err != nil {
			return out, jsonbind.FieldError("height", "invalid float64", err)
		}
		out.Height = v
	}
	if raw, ok := m["points"]; ok {
		arr, err := jsonbind.RawJSONArray(raw)
		if err != nil {
			return out, err
		}
		slice := make([]SourceCanvasPoint, 0, len(arr))
		for _, el := range arr {
			item, err := decodeSourceCanvasPointJSON(el)
			if err != nil {
				return out, err
			}
			slice = append(slice, item)
		}
		out.Points = slice
	}
	if raw, ok := m["strokes"]; ok {
		arr, err := jsonbind.RawJSONArray(raw)
		if err != nil {
			return out, err
		}
		slice := make([]SourceAnnotationStroke, 0, len(arr))
		for _, el := range arr {
			item, err := decodeSourceAnnotationStrokeJSON(el)
			if err != nil {
				return out, err
			}
			slice = append(slice, item)
		}
		out.Strokes = slice
	}
	if raw, ok := m["start"]; ok {
		v, err := decodeSourceAnnotationAnchorJSON(raw)
		if err != nil {
			return out, err
		}
		out.Start = v
	}
	if raw, ok := m["end"]; ok {
		v, err := decodeSourceAnnotationAnchorJSON(raw)
		if err != nil {
			return out, err
		}
		out.End = v
	}
	if raw, ok := m["text"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("text", "invalid string", err)
		}
		out.Text = v
	}
	if raw, ok := m["color"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("color", "invalid string", err)
		}
		out.Color = v
	}
	if raw, ok := m["fill"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("fill", "invalid string", err)
		}
		out.Fill = v
	}
	if raw, ok := m["strokeWidth"]; ok {
		v, err := jsonbind.DecodeJSONFloat64(raw)
		if err != nil {
			return out, jsonbind.FieldError("strokeWidth", "invalid float64", err)
		}
		out.StrokeWidth = v
	}
	if raw, ok := m["layer"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("layer", "invalid string", err)
		}
		out.Layer = v
	}
	if raw, ok := m["zIndex"]; ok {
		v, err := jsonbind.DecodeJSONInt(raw)
		if err != nil {
			return out, jsonbind.FieldError("zIndex", "invalid int", err)
		}
		out.ZIndex = v
	}
	return out, nil
}

func encodeExchangeDocumentMap(v ExchangeDocument) map[string]any {
	body := map[string]any{}
	body["$schema"] = v.Schema
	body["formatVersion"] = v.FormatVersion
	body["project"] = encodeExchangeProjectMap(v.Project)
	{
		arr := make([]any, len(v.Models))
		for i := range v.Models {
			arr[i] = encodeExchangeModelMap(v.Models[i])
		}
		body["models"] = arr
	}
	{
		arr := make([]any, len(v.Domains))
		for i := range v.Domains {
			arr[i] = encodeExchangeDomainMap(v.Domains[i])
		}
		body["domains"] = arr
	}
	{
		arr := make([]any, len(v.Vocabulary))
		for i := range v.Vocabulary {
			arr[i] = encodeExchangeVocabularyEntryMap(v.Vocabulary[i])
		}
		body["vocabulary"] = arr
	}
	{
		arr := make([]any, len(v.Relationships))
		for i := range v.Relationships {
			arr[i] = encodeExchangeRelationshipMap(v.Relationships[i])
		}
		body["relationships"] = arr
	}
	{
		arr := make([]any, len(v.Processes))
		for i := range v.Processes {
			arr[i] = encodeExchangeProcessMap(v.Processes[i])
		}
		body["processes"] = arr
	}
	{
		arr := make([]any, len(v.DataFlows))
		for i := range v.DataFlows {
			arr[i] = encodeExchangeDataFlowMap(v.DataFlows[i])
		}
		body["dataFlows"] = arr
	}
	{
		arr := make([]any, len(v.CRUDAssignments))
		for i := range v.CRUDAssignments {
			arr[i] = encodeExchangeCRUDAssignmentMap(v.CRUDAssignments[i])
		}
		body["crudAssignments"] = arr
	}
	return body
}

func encodeExchangeDocument(w io.Writer, v ExchangeDocument) error {
	return json.NewEncoder(w).Encode(encodeExchangeDocumentMap(v))
}

func encodeExchangeProjectMap(v ExchangeProject) map[string]any {
	body := map[string]any{}
	body["id"] = v.ID
	return body
}

func encodeExchangeProject(w io.Writer, v ExchangeProject) error {
	return json.NewEncoder(w).Encode(encodeExchangeProjectMap(v))
}

func encodeExchangeModelMap(v ExchangeModel) map[string]any {
	body := map[string]any{}
	body["id"] = v.ID
	body["names"] = encodeNamesMap(v.Names)
	body["description"] = v.Description
	body["role"] = v.Role
	body["usageScope"] = v.UsageScope
	{
		arr := make([]any, len(v.Fields))
		for i := range v.Fields {
			arr[i] = encodeExchangeFieldMap(v.Fields[i])
		}
		body["fields"] = arr
	}
	{
		arr := make([]any, len(v.PhysicalColumns))
		for i := range v.PhysicalColumns {
			arr[i] = encodeExchangePhysicalColumnMap(v.PhysicalColumns[i])
		}
		body["physicalColumns"] = arr
	}
	{
		arr := make([]any, len(v.Indexes))
		for i := range v.Indexes {
			arr[i] = encodeSourceIndexDefinitionMap(v.Indexes[i])
		}
		body["indexes"] = arr
	}
	body["partitioning"] = encodeSourcePartitionSchemeMap(v.Partitioning)
	body["additionalSql"] = v.AdditionalSQL
	return body
}

func encodeExchangeModel(w io.Writer, v ExchangeModel) error {
	return json.NewEncoder(w).Encode(encodeExchangeModelMap(v))
}

func encodeExchangeFieldMap(v ExchangeField) map[string]any {
	body := map[string]any{}
	body["id"] = v.ID
	body["names"] = encodeNamesMap(v.Names)
	body["primaryKey"] = v.PrimaryKey
	body["important"] = v.Important
	body["domainId"] = v.DomainID
	body["required"] = v.Required
	body["unique"] = v.Unique
	body["defaultValue"] = encodeSourceColumnDefaultMap(v.DefaultValue)
	body["valueGeneration"] = v.ValueGeneration
	return body
}

func encodeExchangeField(w io.Writer, v ExchangeField) error {
	return json.NewEncoder(w).Encode(encodeExchangeFieldMap(v))
}

func encodeExchangePhysicalColumnMap(v ExchangePhysicalColumn) map[string]any {
	body := map[string]any{}
	body["id"] = v.ID
	body["sourceFieldId"] = v.SourceFieldID
	body["domainId"] = v.DomainID
	body["componentId"] = v.ComponentID
	body["names"] = encodeNamesMap(v.Names)
	body["primitiveType"] = v.PrimitiveType
	body["required"] = v.Required
	body["primaryKey"] = v.PrimaryKey
	body["unique"] = v.Unique
	body["resolved"] = v.Resolved
	return body
}

func encodeExchangePhysicalColumn(w io.Writer, v ExchangePhysicalColumn) error {
	return json.NewEncoder(w).Encode(encodeExchangePhysicalColumnMap(v))
}

func encodeExchangeDomainMap(v ExchangeDomain) map[string]any {
	body := map[string]any{}
	body["id"] = v.ID
	body["names"] = encodeNamesMap(v.Names)
	body["categoryId"] = v.CategoryID
	body["shape"] = v.Shape
	body["primitiveType"] = v.PrimitiveType
	body["bits"] = v.Bits
	body["unsigned"] = v.Unsigned
	body["length"] = v.Length
	body["precision"] = v.Precision
	body["scale"] = v.Scale
	body["codeSetBaseType"] = v.CodeSetBaseType
	{
		arr := make([]any, len(v.CodeSetEntries))
		for i := range v.CodeSetEntries {
			arr[i] = encodeSourceCodeSetEntryMap(v.CodeSetEntries[i])
		}
		body["codeSetEntries"] = arr
	}
	{
		arr := make([]any, len(v.Components))
		for i := range v.Components {
			arr[i] = encodeSourceDomainComponentMap(v.Components[i])
		}
		body["components"] = arr
	}
	body["partitionKey"] = v.PartitionKey
	body["system"] = v.System
	return body
}

func encodeExchangeDomain(w io.Writer, v ExchangeDomain) error {
	return json.NewEncoder(w).Encode(encodeExchangeDomainMap(v))
}

func encodeExchangeVocabularyEntryMap(v ExchangeVocabularyEntry) map[string]any {
	body := map[string]any{}
	body["id"] = v.ID
	body["names"] = encodeNamesMap(v.Names)
	body["meaning"] = v.Meaning
	body["memo"] = v.Memo
	body["aliases"] = v.Aliases
	return body
}

func encodeExchangeVocabularyEntry(w io.Writer, v ExchangeVocabularyEntry) error {
	return json.NewEncoder(w).Encode(encodeExchangeVocabularyEntryMap(v))
}

func encodeExchangeRelationshipMap(v ExchangeRelationship) map[string]any {
	body := map[string]any{}
	body["id"] = v.ID
	body["name"] = v.Name
	body["sourceId"] = v.SourceID
	body["targetId"] = v.TargetID
	body["sourceMultiplicity"] = v.SourceMultiplicity
	body["targetMultiplicity"] = v.TargetMultiplicity
	body["direction"] = v.Direction
	body["kind"] = v.Kind
	body["onDelete"] = v.OnDelete
	body["referenceId"] = v.ReferenceID
	body["primaryKey"] = v.PrimaryKey
	body["foreignKey"] = v.ForeignKey
	body["ownerModelId"] = v.OwnerModelID
	body["childModelId"] = v.ChildModelID
	return body
}

func encodeExchangeRelationship(w io.Writer, v ExchangeRelationship) error {
	return json.NewEncoder(w).Encode(encodeExchangeRelationshipMap(v))
}

func encodeExchangeProcessMap(v ExchangeProcess) map[string]any {
	body := map[string]any{}
	body["id"] = v.ID
	body["name"] = v.Name
	body["description"] = v.Description
	body["kind"] = v.Kind
	{
		arr := make([]any, len(v.PhysicalProcesses))
		for i := range v.PhysicalProcesses {
			arr[i] = encodeSourceDFDPhysicalProcessMap(v.PhysicalProcesses[i])
		}
		body["physicalProcesses"] = arr
	}
	return body
}

func encodeExchangeProcess(w io.Writer, v ExchangeProcess) error {
	return json.NewEncoder(w).Encode(encodeExchangeProcessMap(v))
}

func encodeExchangeDataFlowMap(v ExchangeDataFlow) map[string]any {
	body := map[string]any{}
	body["id"] = v.ID
	body["canvasId"] = v.CanvasID
	body["sourceId"] = v.SourceID
	body["destinationId"] = v.DestinationID
	body["label"] = v.Label
	body["protocol"] = v.Protocol
	body["bidirectional"] = v.Bidirectional
	return body
}

func encodeExchangeDataFlow(w io.Writer, v ExchangeDataFlow) error {
	return json.NewEncoder(w).Encode(encodeExchangeDataFlowMap(v))
}

func encodeExchangeCRUDAssignmentMap(v ExchangeCRUDAssignment) map[string]any {
	body := map[string]any{}
	body["flowId"] = v.FlowID
	body["processUnitId"] = v.ProcessUnitID
	body["modelId"] = v.ModelID
	body["operations"] = v.Operations
	return body
}

func encodeExchangeCRUDAssignment(w io.Writer, v ExchangeCRUDAssignment) error {
	return json.NewEncoder(w).Encode(encodeExchangeCRUDAssignmentMap(v))
}

func decodeMarkdownOptionsBytes(data []byte) (MarkdownOptions, error) {
	return decodeMarkdownOptionsJSON(json.RawMessage(data))
}

func decodeMarkdownOptionsJSON(raw json.RawMessage) (MarkdownOptions, error) {
	var out MarkdownOptions
	m, err := jsonbind.RawJSONMap(raw)
	if err != nil {
		return out, err
	}
	if raw, ok := m["nameMode"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("nameMode", "invalid string", err)
		}
		out.NameMode = v
	}
	if raw, ok := m["modelCardContent"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("modelCardContent", "invalid string", err)
		}
		out.ModelCardContent = v
	}
	if raw, ok := m["generatedAt"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("generatedAt", "invalid string", err)
		}
		out.GeneratedAt = v
	}
	if raw, ok := m["sourceSnapshotRevision"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("sourceSnapshotRevision", "invalid string", err)
		}
		out.SourceSnapshotRevision = v
	}
	return out, nil
}

func decodeSQLExportOptionsBytes(data []byte) (SQLExportOptions, error) {
	return decodeSQLExportOptionsJSON(json.RawMessage(data))
}

func decodeSQLExportOptionsJSON(raw json.RawMessage) (SQLExportOptions, error) {
	var out SQLExportOptions
	m, err := jsonbind.RawJSONMap(raw)
	if err != nil {
		return out, err
	}
	if raw, ok := m["dialects"]; ok {
		v, err := jsonbind.DecodeJSONStringSlice(raw)
		if err != nil {
			return out, err
		}
		out.Dialects = v
	}
	if raw, ok := m["modelIds"]; ok {
		v, err := jsonbind.DecodeJSONStringSlice(raw)
		if err != nil {
			return out, err
		}
		out.ModelIDs = v
	}
	return out, nil
}

func decodeDiagramExportOptionsBytes(data []byte) (DiagramExportOptions, error) {
	return decodeDiagramExportOptionsJSON(json.RawMessage(data))
}

func decodeDiagramExportOptionsJSON(raw json.RawMessage) (DiagramExportOptions, error) {
	var out DiagramExportOptions
	m, err := jsonbind.RawJSONMap(raw)
	if err != nil {
		return out, err
	}
	if raw, ok := m["nameMode"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("nameMode", "invalid string", err)
		}
		out.NameMode = v
	}
	if raw, ok := m["modelCardContent"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("modelCardContent", "invalid string", err)
		}
		out.ModelCardContent = v
	}
	if raw, ok := m["crudOrientation"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("cRUDOrientation", "invalid string", err)
		}
		out.CRUDOrientation = v
	}
	return out, nil
}

func encodeExportArtifactMap(v ExportArtifact) map[string]any {
	body := map[string]any{}
	body["path"] = v.Path
	body["mediaType"] = v.MediaType
	body["content"] = v.Content
	return body
}

func encodeExportArtifact(w io.Writer, v ExportArtifact) error {
	return json.NewEncoder(w).Encode(encodeExportArtifactMap(v))
}

func encodeDiagnosticTargetMap(v DiagnosticTarget) map[string]any {
	body := map[string]any{}
	body["kind"] = v.Kind
	body["modelId"] = v.ModelID
	body["fieldId"] = v.FieldID
	body["domainId"] = v.DomainID
	body["relationshipId"] = v.RelationshipID
	return body
}

func encodeDiagnosticTarget(w io.Writer, v DiagnosticTarget) error {
	return json.NewEncoder(w).Encode(encodeDiagnosticTargetMap(v))
}

func encodeExportDiagnosticMap(v ExportDiagnostic) map[string]any {
	body := map[string]any{}
	body["severity"] = v.Severity
	body["code"] = v.Code
	body["message"] = v.Message
	body["exportMode"] = v.ExportMode
	body["artifactId"] = v.ArtifactID
	body["sourceKind"] = v.SourceKind
	body["sourceId"] = v.SourceID
	body["sourcePath"] = v.SourcePath
	body["canvasId"] = v.CanvasID
	body["editorTarget"] = v.EditorTarget
	body["suggestedFix"] = v.SuggestedFix
	body["target"] = encodeDiagnosticTargetMap(v.Target)
	return body
}

func encodeExportDiagnostic(w io.Writer, v ExportDiagnostic) error {
	return json.NewEncoder(w).Encode(encodeExportDiagnosticMap(v))
}

func encodeExportResultMap(v ExportResult) map[string]any {
	body := map[string]any{}
	{
		arr := make([]any, len(v.Artifacts))
		for i := range v.Artifacts {
			arr[i] = encodeExportArtifactMap(v.Artifacts[i])
		}
		body["artifacts"] = arr
	}
	{
		arr := make([]any, len(v.Diagnostics))
		for i := range v.Diagnostics {
			arr[i] = encodeExportDiagnosticMap(v.Diagnostics[i])
		}
		body["diagnostics"] = arr
	}
	return body
}

func encodeExportResult(w io.Writer, v ExportResult) error {
	return json.NewEncoder(w).Encode(encodeExportResultMap(v))
}
